class FastFrameCheckSequence16:
    def __init__(self) -> None: ...
    def update(self, byte: int) -> int: ...
    @property
    def is_good(self) -> bool: ...
    @property
    def checksum(self) -> int: ...
    @staticmethod
    def compute_checksum(data: bytes, start: int, length: int) -> int: ...
