from typing import Dict, List

NEK_HAN_FIELD_OBIS_LIST_VER_ID: str
NEK_HAN_FIELD_METER_ID: str
NEK_HAN_FIELD_METER_TYPE: str
NEK_HAN_FIELD_METER_MANUFACTURER: str
NEK_HAN_FIELD_METER_DATETIME: str
NEK_HAN_FIELD_ACTIVE_POWER_IMPORT: str
NEK_HAN_FIELD_ACTIVE_POWER_EXPORT: str
NEK_HAN_FIELD_REACTIVE_POWER_IMPORT: str
NEK_HAN_FIELD_REACTIVE_POWER_EXPORT: str
NEK_HAN_FIELD_CURRENT_L1: str
NEK_HAN_FIELD_CURRENT_L2: str
NEK_HAN_FIELD_CURRENT_L3: str
NEK_HAN_FIELD_VOLTAGE_L1: str
NEK_HAN_FIELD_VOLTAGE_L2: str
NEK_HAN_FIELD_VOLTAGE_L3: str
NEK_HAN_FIELD_ACTIVE_POWER_IMPORT_HOUR: str
NEK_HAN_FIELD_ACTIVE_POWER_EXPORT_HOUR: str
NEK_HAN_FIELD_REACTIVE_POWER_IMPORT_HOUR: str
NEK_HAN_FIELD_REACTIVE_POWER_EXPORT_HOUR: str
name_obis_map: Dict[str, List[str]]
obis_name_map: Dict[str, str]
